### ISSUE TITLE
Great job! 

### ISSUE THREAD

**Issue by sohailc** [kafonek/ipython_blocking#1]
Hi Mat, 

This is not so much an issue as it is an encouragement on your work with `ipython_blocking`. Its exactly what I was looking for, for hours today.   

I will definitely send feedback if I have any and submit PR's if I can. 

Thanks again!

Sohail

**Comment by kafonek** [comment]
Thanks so much Sohail!  I just released `ipython_blocking` 0.2.0, which has a new magic function `%blockrun`.  That new capability only accepts an `ipywidgets.Button` object but it adds a "cell -> run all below" style handler so that the widget will "block and run all".  That was the main 'gap' I heard about from the initial release of `ipython_blocking`.

If you have use-cases that aren't met in your Enterprise, please let me know about them!

Thanks again.
