### ISSUE TITLE
how to block python code execution till js snippet returns in Jupyter notebook

### ISSUE THREAD

**Issue by theSuiGenerisAakash** [kafonek/ipython_blocking#4]
I am trying to execute a JS code to get the notebook name in Jupyter

```
import IPython
from IPython.core.magics.display import Javascript

def func():
    return Javascript("IPython.notebook.kernel.execute(`notebook_name = '${IPython.notebook.notebook_name}'`)")
func()
```

The problem is that this code is executed asynchronously and I do not have the result until all cells have finished executing whereas I need the result much before. This creates a problem when I am trying to do a **Run all cells** or **%run notebook.ipynb** from another notebook where the notebook.ipynb file holds this js code. I tried using 
```
%block func
```

but it doesn't work.

Help is much obliged.

**Comment by kafonek** [comment]
Hi @theSuiGenerisAakash, I'm afraid I don't have a good answer for you.  What's happening is that `func()` is getting executed and returns a `Javascript` object that evaluates as `True` if you `bool()` it.  That gets you out of the `%block` command immediately.  

When the Python kernel receives the code and executes it, it's actually sending another message asynchronously back to the front end to execute the javascript (setting `notebook_name`).  When the front-end receives that, it sends a `execute_request` message to the Python kernel (again asynchronously) to eval that Python code (`notebook_name = 'Untitled.ipynb'` or whatever your name is).  

I believe if you keep fiddling, you'll get to something like this:

```python
### cell 1
import ipython_blocking
import IPython
from IPython.core.magics.display import Javascript
Javascript("IPython.notebook.kernel.execute(`notebook_name = '${IPython.notebook.notebook_name}'`)")

### cell 2
def block():
    try:
        return notebook_name
    except NameError:
        pass

### cell 3
%block block

### cell 4
print(notebook_name)
```

If you run those cells manually with a second or so pause in between, then it will work and `notebook_name` is set.  However if you `cell -> run all` it will block forever.  Ultimately `ipython_blocking` is only good for blocking and capturing/replaying `execute_request` messages while watching `comm_msg` (widget changes) in order to break out of the context.  In the example above, the `execute_request` `notebook_name = ...` message that's eventually getting triggered asynchronously by the first cell gets queued up behind cell 3 and is captured instead of executed, so you'll never break out of the context.

I'm afraid you'll have to look around for other options to get your notebook name within the Notebook.  Thanks.

**Comment by theSuiGenerisAakash** [comment]
This is as I had thought, thanks for the detailed explanation. Please let me know if I should close the issue.
