### ISSUE TITLE
I’m trying to use it within voila

### ISSUE THREAD

**Issue by atwahsz** [kafonek/ipython_blocking#9]
I was not able get it to work. 
Is it possible to make it rerun a specific cell instead of blocking?

**Comment by kafonek** [comment]
@atwahsz unfortunately `ipython_blocking` is not compatible with Voila because Voila explicitly disallows `execute_request` messages being handled by the kernel, and `ipython_blocking` relies on using those to "replay" captured (blocking) cells.  I believe the relevant Voila code is at https://github.com/voila-dashboards/voila/blob/master/voila/app.py#L411, and you can read more about the different kinds of messages sent to the kernel at https://jupyter-client.readthedocs.io/en/stable/messaging.html#.

Another way to think about it is that Voila runs every cell when you open the dashboard, and then disallows all Python code execution after that.  You can't add new cells, edit cells, or even send Python code over the Javascript/websocket interface (which is what executing cells does anyways).  `ipython_blocking` is effectively trying to run new Python code after the block action is resolved, and Voila won't let it.

Hope that helps put it in context, even though it doesn't help your use case.
